#!/bin/sh
#/etc/init.d/vhsys

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec sudo forever start --sourceDir=/home/pi/vhsys -p /home/pi/vhsys/.tmp-forever --minUptime 86400000 --silent app.js
  ;;
stop)
  exec sudo forever stopall
  ;;
*)
  echo "Usage: /etc/init.d/vhsys {start|stop}"
  exit 1
  ;;
esac

exit 0
